# ===========================================
# Property Onboarding Service (Producer)
# ===========================================

server.port=8081

# --- Kafka Producer Configuration ---
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# --- Application: Kafka Topic ---
app.kafka.topic=property-onboarding-events
